spring.application.name=themealdb-api
spring.datasource.url=jdbc:postgresql://localhost:5432/themealdb
spring.datasource.username=postgres
spring.datasource.password=football123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=e67d69b34fe85c67c3d19a7d22cfc6f465f80d226d913020e54e9f85e20cbffb
jwt.expiration=86400000